apiVersion: v1
kind: Service
metadata:
  name: kali-service
  namespace: cyber-lab
spec:
  type: NodePort
  selector:
    app: kali
  ports:
  - protocol: TCP
    port: 6080
    targetPort: 6080
    nodePort: 31000
    name: novnc
  - protocol: TCP
    port: 5901  # Cambiar de 5900 a 5901
    targetPort: 5901  # Cambiar de 5900 a 5901
    nodePort: 31001
    name: vnc
