apiVersion: v1
kind: Service
metadata:
  name: metasploitable-service
  namespace: cyber-lab
spec:
  type: NodePort
  selector:
    app: metasploitable
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31002
    name: http
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 31003
    name: ssh
